[pycodestyle]
max_line_length = 120
ignore = E501,W6

[tool.autopep8]
ignore = "E501,W6"
in-place = true
recursive = true
aggressive = 3
line-length = 120

[tool.black]
line-length = 120

[tool.pydocstyle]
max-line-length = 80
