[tool.autopep8]
max_line_length = 120
ignore = ["E501", "W6"]

[tool.flake8]
max-line-length = 120

[tool.pycodestyle]
max_line_length = 120
ignore = ["E501", "W6"]

[tool.pydocstyle]
max-line-length = 80

[tool.pyright]
exclude = [
	"**/node_modules",
	"**/__pycache__",
	"**/.*",
	"tmp",
]
